### ISSUE TITLE
Help wanted: National Civic Day of Hacking calendar event for FOSS@RIT

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/fossrit.github.io#160]
# Summary

Post up a [calendar event](https://fossrit.github.io/calendar/) on the FOSS@RIT site for "National Civic Day of Hacking" coming up on 12 September 2020

# Background

@itprofjacobs shared [National Civic Day of Hacking](https://www.meetup.com/Rochester-National-Day-of-Civic-Hacking-Cohort/events/272989570/) coming up on 12 September 2020:

> Join The City of Rochester and RIT for the 2020 National Day of Civic Hacking, which brings together civic leaders, public servants, designers, coders, and engaged citizens to partner with local government and community groups to tackle some of our toughest challenges.
>
>This year, we invite you to join us for a day of collective action to help those most in need of social safety net services during COVID-19. Have other pressing issues in your community that you’d like to work on? You’re welcome to join too! Everyone is welcome! No previous experience, expertise, or prep-work required!

# Details

See the Runbook page for guidance on how to do this:

## https://runbook.fossrit.community/infra/website/#how-to-add-calendar-events

# Outcome

More people know about the National Civic Day of Hacking event this year! :tada:

**Comment by ct-martin** [comment]
Not sure where this info got dropped, but you actually don't need a separate page for the calendar event! If it's in the `events` category and the code hasn't changed it should just need the front matter (`date-start`, etc. in the regular event page)

**Comment by jwflory** [comment]
Oh cool! That's helpful to know, thanks @ct-martin. I'm closing this issue as a duplicate.
