### ISSUE TITLE
update links to Matrix room

### ISSUE THREAD

**Issue by MoralCode** [FOSSRIT/fossrit.github.io#176]
From @Nolski :
> since the freenode channel blew up, so did our matrix bridging and our matrix room and our #rit-foss libera channel are no longer bridged. I think we should just change the matrix link on the website to point to the matrix->libera channel through the riot app.

see also some discussion in https://riot.im/app/#/room/#rit-foss:mozilla.org

**Comment by jwflory** [comment]
This would be a great Hacktoberfest fix.

**Comment by MoralCode** [comment]
seems like https://app.element.io/#/room/#rit-foss:libera.chat is probably the correct link (at least for viewing the libera IRC channel in matrix).

Personally id probably prefer to use a generic link that isnt specific to one particular client, such as https://matrix.to/#/#rit-foss:libera.chat, but either one should work. Is there a preference as to which link should be used?
