### ISSUE TITLE
Document how to make a development environment in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/fossrit.github.io#19]
There needs to be a better explanation of how to set up a development environment for this Jekyll project. Currently, I'm testing by pushing things to production because I haven't figured out how to do this yet. :confused:

I need to follow up with @ct-martin to figure out how he is doing this, from some of our in-person conversations.

---

**Edit 1**: See Christian's comment [here](https://github.com/RITlug/ritlug.github.io/issues/170#issuecomment-442690894): "_Jekyll can watch for changes and rebuild. So I run bundle exec jekyll serve (once Jekyll is installed) and then wait every time I save a file for it to rebuild_"

**Comment by ct-martin** [comment]
We've been discussing this in RITlug/ritlug.github.io#170. Here's the Jekyll docs link: https://jekyllrb.com/docs/installation/other-linux/

I was planning to do a bunch of docs this month but it's been crazy.

**Comment by jwflory** [comment]
I think I can use containers with this:

```bash
JEKYLL_VERSION=3.8

docker run --rm \
    -p 4000:4000 \
    -v "$PWD:/srv/jekyll:Z" \
    -it jekyll/jekyll:$JEKYLL_VERSION \
    sh -c "jekyll serve --watch"
```

But I'm getting an annoying error now:

```
FATAL: Listen error: unable to monitor directories for changes.
Visit https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for info on how to fix this.
```

I'll debug this further later.
