### ISSUE TITLE
Add CI tests for new pull requests

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/fossrit.github.io#44]
Setting up CI tests to ensure new contributions don't break the website will be helpful. Travis CI is my preferred tool of choice for this because of the close integration with a GitHub workflow. Maybe it's better to knock out #36 for this first though. Needs some investigation.

**Comment by ritjoe** [comment]
Would this incorporate some sort of webcrawler to test for broken links? 

If so, I'll leave this notion in this issue. If not, I'll open a new issue to propose it.

**Comment by jwflory** [comment]
@ritjoe No, I think it's separate. You can open a new issue to discuss it.

**Comment by jwflory** [comment]
This is implemented in #114. It took a while, but we finally have working CI, and it even includes a handy tool to crawl for broken links. A few of them already came up in #115. :smile: 

This issue will be closed soon.
