### ISSUE TITLE
Scale images in Jekyll posts better for mobile devices

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/fossrit.github.io#45]
# Summary

Scale images in announcements / Jekyll posts automatically for mobile devices

# Background

When an image is used in a new Jekyll post, if the image is large, it doesn't scale correctly. The horizontal scrolling is disrupted and the image flows off of the page. It disrupts the browsing experience. A better way is to downscale the image appropriately for the screen size of the current device.

![Screenshot of poor scaling of images on mobile devices](https://user-images.githubusercontent.com/4721034/51330177-fb6f8980-1a44-11e9-9a1f-2f128db9d4b8.png "Screenshot of poor scaling of images on mobile devices")

# Details

This is new to me. Need to figure out best way to do this with how the site is currently set up.

# Outcome

Better mobile browsing experience when images are used in Jekyll posts

**Comment by jwflory** [comment]
For what it's worth, I was manually able to make responsive images in individual blog posts, but I should figure out a way to make this happen on all images in announcements by default:

`<a alt="Flory delivers presentation to UNICEF Innovation Fund cohort" title="Flory delivers presentation to UNICEF Innovation Fund cohort" href="https://twitter.com/utopiah/status/1112801875764576256"><img src="/img/announcements/2019/04/unicef-flory.jpg" width="auto" width="100%"/></a>`

**Comment by ct-martin** [comment]
Bootstrap has a `.img-fluid` class for this

**Comment by jwflory** [comment]
Haven't dug in deep but this looks interesting. I also want to see if we can add a cleaner way to do alt tags in images too:

https://github.com/mmistakes/jekyll-picture-tag
