### ISSUE TITLE
Creating resources for onboarding

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/fossrit.github.io#5]
# Problem

When visiting the website, it's unclear how to get involved with FOSS@MAGIC or what you have to do to "be a part of the {club,group,secret society,etc.}".
# Analysis

We need to have some clearly documented steps about how a student, either current or incoming, can become involved with the FOSS@MAGIC program. This is a bigger topic than maybe just a website, but as students and alumni, we can maybe offer specific points about how someone can get involved.

A numbered, ordered list of steps that can be accomplished (and easy to think of as "accomplished" or "complete") is needed. The steps would be highlighted on the main page to introduce students for how to participate, things they can try working on to get started, and other ideas for participating. The end result of this "onboarding" guide would be getting "added" to the GitHub organization as a visible form of recognizing the person completing the steps.

This accomplishes the purpose of:
1. Supporting existing program with more easily accessible info
2. Ensure longevity of program by clearly having steps to get involved
3. Bring in new students with goal of turning them from participants => contributors
# Implementation
1. Brainstorm ideas of participation in the program from a student perspective
2. Organize ideas into ordered list of tasks
3. Come with a way to "verify" completion [*]
4. Create visual steps with links / help for completing every step on the site
5. Deploy!

[*] _Note_: I don't want this to be too heavy on "verification" or proving your work… more like a simple check. It's not about indoctrinating people into a secret society or team – we want it to be easy for interested people to become involved and then move up in participation and activity over time.

**Comment by Nolski** [comment]
I suggest we break this down into more specific bugs. Lets think about what we can do with just this website. Some suggestions I've seen:

-  Link to telegram thinger
- Current/Next location of a fossbox gathering space
- About giving the deets on what the fossbox actually is.

I'd be happy to put this stuff on the website and make it all nice and stuff if someone wants to write the copy.

**Comment by jflory7** [comment]
I think this one is probably best broken into smaller issues just because onboarding is a really big topic and not entirely related to placing it on the website.

I can try working on the copy soon.

**Comment by ritjoe** [comment]
I was looking briefly at the web site open issues when I saw this again. The need remains. 

I began listing some things in imperative mood (ie, what is recommended also for git commit messages). It is at best a stub, but perhaps could be a useful starting point or point of comparison with other resources that have been deployed since this issue was opened.

Instead of faffing around a lot more improving it and figuring out where exactly in the RIT stable of resources it should go, I just tossed it into my blog:

http://deejoe.etrumeus.com/update/joining-ritfoss.html

If the CC-BY-SA license on my blog is not suited for some use to which one might want to put it, let me know and we can work something out.

**Comment by jwflory** [comment]
Soooo, it's been a while here. Provided that the Runbook is now a thing, and that we now have a functioning website (when this issue was opened, fossrit.github.io was a one-page site about FOSS Hours), I'm going to close this issue as a `duplicate`. :clapper: 

I opened a new issue, FOSSRIT/runbook#36, to track @ritjoe's above comment.
