### ISSUE TITLE
Add 1-click links for IRC

### ISSUE THREAD

**Issue by ritjoe** [FOSSRIT/fossrit.github.io#6]
We probably want to build on this with some brief getting-started guides for Matrix and (possibly) Telegram integrations, but this IMNSHO is the place to start. 

Need help identifying a reasonable icon to use for an IRC button at the bottom of the initial view of the page, but putting 

http://webchat.freenode.net/?&channels=rit-foss

there is a quick to implement, quick to use, relatively easy and so potentially very useful first step in revamping our overall presentation to help people find us to talk with us.

We are always going to have a sort of raggedy back-end of lots of sites where things are or once were going on. We aren't going to solve that. But we can make the front end mesh better with where things are happening now, and top of the line there is IRC (with its various integrations).

**Comment by ritjoe** [comment]
If anyone can find a reduced-palette version of something like this that looks OK it might work:

https://commons.wikimedia.org/wiki/File:Chat_bubbles.svg

**Comment by Nolski** [comment]
Does riot also support 1-click links? Might be nice for those looking to get setup with that too.

**Comment by Nolski** [comment]
Also, one of these will probably work.

http://fontawesome.io/icon/comments-o/
http://fontawesome.io/icon/comments/
http://fontawesome.io/icon/comment/
http://fontawesome.io/icon/comment-o/
