### ISSUE TITLE
Add instructions for non-Docker local testing before opening a PR

### ISSUE THREAD

**Issue by ghost** [FOSSRIT/fossrit.github.io#79]
I believe @jrtechs mentioned maybe being able to contribute something here? 

Might do to see if something has been added along these lines to https://github.com/RITlug/ritlug.github.io

This is complementary to, but in a way in the opposite direction from, #36

**Comment by ritjoe** [comment]
Github is throwing errors on these submissions for me, so this is a duplicate. Closing.

**Comment by jrtechs** [comment]
Yeah, I've been having similar issues all morning with Github.
